name: mani_vitac
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py310h130f0dd_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py310_cu118
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu118
  - typing_extensions=4.7.1=py310h06a4308_0
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - ansi2html==1.8.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==23.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.0
      - configargparse==1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.5
      - dash==2.14.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.18.1
      - flask==3.0.0
      - fonttools==4.44.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.2
      - gymnasium==0.29.1
      - importlib-metadata==6.8.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isort==5.12.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lxml==4.9.3
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - meshio==5.3.4
      - nbformat==5.7.0
      - nest-asyncio==1.5.8
      - numpy==1.26.0
      - oauthlib==3.2.2
      - open3d==0.17.0
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.3
      - path==16.7.1
      - path-py==12.5.0
      - pexpect==4.8.0
      - platformdirs==4.0.0
      - plotly==5.18.0
      - pooch==1.8.0
      - prompt-toolkit==3.0.41
      - protobuf==4.23.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - python-dateutil==2.8.2
      - python-fcl==0.7.0.5
      - pytz==2023.3.post1
      - pyvista==0.42.3
      - pyyaml==6.0.1
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rich==13.6.0
      - rpds-py==0.12.0
      - rsa==4.9
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      # - sapien==3.0.0.dev20231112
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - scooby==0.9.2
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - stable-baselines3==2.1.0
      - stack-data==0.6.3
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tetgen==0.6.3
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transforms3d==0.4.1
      - trimesh==4.0.4
      - tzdata==2023.3
      - vtk==9.2.6
      - wandb==0.16.0
      - warp==1.0.4
      - warp-lang==1.0.0b2
      - wcwidth==0.2.10
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - zipp==3.17.0
